### ISSUE TITLE
Add extension to Firefox

### ISSUE THREAD

**Issue by NathanVerkerk** [Vertco/TriggerForNinjaOne#11]
Add the extension to the Mozilla add-on store, and add support for Firefox.
@TargetCrafter, you have done some things for Firefox already right?

**Comment by TargetCrafter** [comment]
Yes, I've done some testing already and added "browser_specific_settings" to the manifest,json with the extension ID.

**Comment by TargetCrafter** [comment]
I got all of the functionality working in Firefox while working on #16, so this issue will be closed when that branch closes.
