### ISSUE TITLE
Make a settings menu

### ISSUE THREAD

**Issue by NathanVerkerk** [Vertco/TriggerForNinjaOne#16]
Settings menu with the export and import button and the follow browser option for darkmode

**Comment by NathanVerkerk** [comment]
Is this still needed? Because the dark mode options are all integrated in the ninja webpage.

**Comment by TargetCrafter** [comment]
I would still like to have a settings menu, but perhaps with the following options:
- Enable/ Disable Trigger+ button
- Import/ Export Trigger+ settings
- Enable/ Disable Theme switcher
- Support link
- Website link
- Credits

**Comment by NathanVerkerk** [comment]
Issue merged with #14

**Comment by TargetCrafter** [comment]
I would also like a setting where the user can change which device types are allowed for the trigger button.
I would implement this with a multi select box in the UI. This can then in turn set the deviceDashboards variable in trigger+_variables.js.
